-- Write a query to convert all customer names to uppercase.
-----select upper(Customer_Name) from orders
-- Extract the first 5 characters from Product_Name.
-----select substr(product_name,1,5) as first_five from orders
-- Find the length of each Customer_Name.
-----select customer_name,length(customer_name)as length_name from ORDERS;
-- Replace the word "Rice" with "Premium Rice" in Product_Name.
-----select replace(product_name,'Rice','Premium rice')as updated_value from orders;
-----select customer_name,trim(customer_name)as trimmed_names from orders;
-- Concatenate First_Name and Last_Name as Full_Name.
----select first_name,last_name,first_name||last_name as full_name from orders;
-- Find customers whose names start with 'A'.
-----SELECT * from orders where customer_name like'A%';
-- Extract the domain name from Email_ID.
------??????????
-- Find the position of '@' in Email_ID.
----select email_id,charindex('@',email_id) from orders;
-- Reverse the Product_Name.
-- ---- Convert the first letter of each word in Product_Name to uppercase.
-- Extract the last 3 characters from Order_ID.
----SELECT ORDER_ID,RIGHT(CAST(ORDER_ID AS VARCHAR(20)),3) AS THREE_LAST FROM ORDERS;
-- Count how many times letter 'a' appears in Customer_Name.
----SELECT CUSTOMER_NAME,length(CUSTOMER_NAME)-LENgth(Replace(CUSTOMER_NAME,'a',''))as replaced_value from orders;
-- Mask the last 4 digits of a phone number.
----select phone_num,legth((phone_num)-4)+'****' as masked_num from orders;
-- Split Full_Name into First_Name and Last_Name.
-----???????????
-- Remove all special characters from Product_Code.
-----select product_code,replace(replace(product_code,'-',''),'@','') as cleaned_code from orders;
-- Compare two columns ignoring case sensitivity.
----SELECT *FROM Orders WHERE Column1 = Column2;????????
-- Find customers whose name contains 'kumar'.
----select* from orders where CUSTOMER_NAME like'%kumar%';
-- Pad Order_ID with leading zeros to make it 6 digits.
----select order_id,lpad(order_id,6,'0') as padded_id from orders;
-- Extract substring between two characters.
----select unit_price,round(unit_price,2)as rounded from orders;
-- Find total sales per order.
----select unit_price,quantity,unit_price*Quantity as sales from orders;
-- Calculate average order value.==========
-- select 
--     PRODUCT_NAME, avg(unit_price*quantity)as avg_order_value 
--     from orders 
--     group by(product_name);
-- Find highest product price.=========
-- select max(unit_price)as max_rate 
-- from orders;
-- Find lowest product price.============
-- select min(unit_price)as min_rate 
-- from orders;
-- Calculate percentage discount applied.=======
-- Find modulus of Quantity divided by 2.======
-- select quantity,quantity%2 as modulus from orders;
-- Convert negative values to positive.========
--select quantity,abs(quantity) as positive_values from orders;
-- Truncate price without rounding.========
-- select unit_price,TRUNCATE(unit_price,2) as truncateee_unit from orders;???????????
-- Find square root of total sales.============
-- select sqrt(sum(unit_price*Quantity)) as sqaure_root from orders;
-- Calculate exponential value of a number.========
-- ??????????
-- Calculate power of 2^5.========
--select power(2,5)as ab from dual;
-- Find absolute difference between two prices.====
????????????
-- Calculate sales growth percentage.
-- Find random number between 1 and 100.
select floor(1+(rand()*100)) as rands_num;
-- Divide total sales by number of orders.
-- Find ceiling value of price.
-- Find floor value of price.
-- Convert decimal to integer.
-- Calculate compound interest.